name: VelocyTaxzz
description: "One place for all travel needs."
version: 1.0.1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  dio: ^5.8.0+1
  provider: ^6.1.5
  go_router: ^16.1.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  permission_handler: ^11.3.0
  fluttertoast: ^8.2.12
  geocoding: ^4.0.0
  intl: ^0.20.2
  url_launcher: ^6.3.2
  http: ^1.5.0
  file_picker: ^10.2.4
  flutter_polyline_points: ^3.0.1
  razorpay_flutter: ^1.4.0
  web_socket_channel: ^3.0.3
  flutter_svg: ^2.2.0
  get: ^4.7.2
  lottie: ^3.3.1
  google_api_headers: ^4.5.5
  flutter_google_places_sdk: ^0.4.2+1
  google_places_autocomplete_text_field: ^2.0.0
  sms_autofill: ^2.4.1
  shared_preferences: ^2.5.3
  hive: ^2.2.3
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0


dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/icon.png"

flutter_native_splash:
  color: "#ffffff"  
  image: assets/logo/icon.png
  android: true
  ios: true


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/app_images/
    - assets/app_images/app_icon/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
